---
iwatch::config_file: '/etc/iwatch/iwatch.xml'
iwatch::title: 'WatchList'
iwatch::syslog: '172.31.0.193:3514'
iwatch::path:
  '/etc/ssh':
    recurse: 'enabled'
    events: 'modify'
  '/etc/hosts':
    recurse: 'disabled'
    syslog: 'disabled'
    exec: 'do diff'
  '/tmp':
    recurse: 'enabled'
